import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

// Spec 015 (TICKET005): the per-agent loop prompts are generated byte-identical
// from prompts/shared/ by scripts/generate-agent-prompts.mjs. These tests are
// the drift guard: they fail if a per-agent copy is hand-edited without
// regenerating, or if the canonical loses the {AGENT} token the runner
// substitutes at dispatch.

const AGENTS = ["claude", "codex", "gemini", "grok", "meta"] as const;
const TEMPLATES = ["LOOP.md", "SPRINT-ROLLOVER.md"] as const;

type GeneratorModule = {
  AGENTS: readonly string[];
  TEMPLATES: readonly string[];
  check: () => ReadonlyArray<{ agent: string; template: string; reason: string }>;
};

// scripts/generate-agent-prompts.mjs is plain ESM outside the TS program
// (allowJs is false), so it is imported through a runtime file URL rather than
// a statically-resolved specifier (mirrors tests/security-headers.test.ts).
const generatorUrl = new URL(
  "../../scripts/generate-agent-prompts.mjs",
  import.meta.url
).href;

function readShared(template: string): Buffer {
  return readFileSync(
    new URL(`../../prompts/shared/${template}`, import.meta.url)
  );
}

function readAgent(agent: string, template: string): Buffer {
  return readFileSync(
    new URL(`../../prompts/${agent}/${template}`, import.meta.url)
  );
}

describe("agent prompt consolidation (spec 015)", () => {
  it("keeps every per-agent prompt byte-identical to its shared canonical", () => {
    for (const template of TEMPLATES) {
      const canonical = readShared(template);
      for (const agent of AGENTS) {
        expect(
          readAgent(agent, template).equals(canonical),
          `prompts/${agent}/${template} drifted from prompts/shared/${template}`
        ).toBe(true);
      }
    }
  });

  it("retains the {AGENT} token in each canonical template for runtime substitution", () => {
    for (const template of TEMPLATES) {
      expect(readShared(template).toString("utf8")).toContain("{AGENT}");
    }
  });

  it("reports no drift through the generator's own check()", async () => {
    const mod = (await import(generatorUrl)) as GeneratorModule;
    expect([...mod.AGENTS].sort()).toEqual([...AGENTS].sort());
    expect([...mod.TEMPLATES].sort()).toEqual([...TEMPLATES].sort());
    expect(mod.check()).toEqual([]);
  });
});
